@startuml Software Platform

!include https://raw.githubusercontent.com/worksystems-design/plantuml-flightlevels-lib/develop/defs/fl-wst.iuml

[Software Platform] <<FL2>>
[SW PF Team 1] <<FL1>>
[SW PF Team 2] <<FL1>>
[SW PF Team 3] <<FL1>>
[5P SW Team] <<FL1>>
[4P SW Team] <<FL1>>
[3P SW Team] <<FL1>>

[SW PF Team 1] --> [Software Platform]
[SW PF Team 2] --> [Software Platform]
[SW PF Team 3] --> [Software Platform]
[5P SW Team] --> [Software Platform]
[4P SW Team] --> [Software Platform]
[3P SW Team] --> [Software Platform]

@enduml