@startuml FLS2024 #2

title Work Systems Topology using PlantUML

package FL3 {
  [Strategy]
}

package FL2 {
  [Product 1]
  [Product 2]
  [XFunctional]
}

package FL1 {
  [The Innovators]
  [Team 1]
  [Team 2]
  [Support & Services]
}

[The Innovators] -up->> [Product 1] : contributes
[The Innovators] -up->> [Strategy] : contributes
[Team 1] -up->> [Product 1] : contributes
[Team 2] -up->> [Product 1] : contributes
[Team 2] -up->> [Product 2] : contributes
[Support & Services] -up->> [XFunctional] : contributes
[Product 1] --up->> [Strategy] : contributes
[Product 2] --up->> [Strategy] : contributes

@enduml

